# Generated by Django 4.1 on 2023-01-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeId', models.BigAutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=15, unique=True)),
                ('address', models.CharField(max_length=50, unique=True)),
                ('is_waiting', models.BooleanField()),
                ('is_delete', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('information', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
