# Generated by Django 4.1 on 2023-01-05 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='store',
            table='store',
        ),
    ]
