# Generated by Django 4.1 on 2023-01-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='storeId',
            new_name='store_id',
        ),
    ]
