# Generated by Django 4.1 on 2023-01-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_store_is_delete_alter_store_is_waiting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='storeId',
            new_name='store_id',
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone_num',
            field=models.CharField(max_length=15),
        ),
    ]
