# Generated by Django 4.1 on 2023-01-05 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiting',
            fields=[
                ('waiting_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('phone_num', models.CharField(max_length=20)),
                ('people', models.SmallIntegerField()),
                ('password', models.SmallIntegerField()),
                ('status', models.BooleanField(choices=[('CN', 'CANCELED'), ('WA', 'WAITING'), ('EN', 'ENTERED')], default='WA')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'waiting',
            },
        ),
    ]
