# Generated by Django 4.1 on 2023-01-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='waiting_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
