# Generated by Django 4.1 on 2023-01-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting', '0002_alter_waiting_waiting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiting',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='status',
            field=models.CharField(choices=[('CN', 'CANCELED'), ('WA', 'WAITING'), ('EN', 'ENTERED')], default='WA', max_length=2),
        ),
        migrations.AlterField(
            model_name='waiting',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
